= nfc meal counter


## Ausgangssituation:

Die TNMS-Helfenberg ist eine Schule mit 65 Schülerinnen und Schüler
mit dem Fokus auf Technik, Mathematik und Englisch.
An jedem Schultag wird an die Schüler eine Mahlzeit pro Kopf ausgegeben.
Um die Kosten fürs Essen später zu berechnen
wird zurzeit alles händisch mit protokolliert.


## Ist-Zustand:

Es sind derzeit 5 Leute mit der Abrechnung beschäftigt.
4 KV's die eine Papiertabelle abzeichnen und eine 5. Person
die die Tabelle vorbereitet und nach Kontrolle digitalisiert.


## Problemstellung:

Das händische mit Protokollieren der Kosten ist nicht wirklich zeitaufwendig, aber die verwendete Zeit,
kann für andere nutzvolle Dinge verwendet werden.


## Aufgabenstellung:

Es ist ein Programm zu entwickeln, dass Überprüft, das jede Schülerin und jeder Schüler an der TNMS Helfenberg,
täglich immer eine Mahlzeit bekommt. Die Berechnungen und Kosten werden automatisch mit protokolliert und
anschließend in Excel Tabellen exportiert.


## Ziele:

Unser Ziel ist die Erstellung eines Programmes welches die Abbrechnung, Verwaltung und Protokollierung der täglichen Mahlzeiten vereinfachet.


## Mengengerüst:

Derzeit umfasst die Schüleranzahl rund 65 SchülerInnen
und um unser Program in der Schule verwenden zukönnen muss es in der Lage sein
die Anzahl der Mahlzeiten, Berechnungen der Kosten sowie Abbrechnungen verwalten zu können.

## Use-Case:
[plantuml]
----
        left to right direction
        actor Person

        rectangle {

        Person -- (consumes something)


        }
----


