= Besprechungsprotokoll 22.05.2021
Sandy Tang, Rosalie Mandel, Kelly Tran
1.0, 06.05.2021: Some notes
ifndef::imagesdir[:imagesdir: images]
:icons: font

ifdef::backend-html5[]

icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/asciidoctor-docker-template/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/htl-leonding-college/asciidoctor-docker-template] ‏ ‏ ‎
icon:home[link=https://htl-leonding.github.io/]
endif::backend-html5[]


.Teilnehmer
|===
|anwesend |Verteiler

|Vorname Nachname
|
|TK
|
|TS
|
|MR
|


|===

.Ort und Zeit
[cols=2*]
|===
|Ort
|In der Schule, Präzensunterricht

|von-bis
|Sa. 22.05.2021
|Dauer
|3h 30min
|===



== Begriffe / Befehle
* ATR = Answer To Reset
*  Script - package.sh (wenn Änderung im Code durchgeführt werden)
** Script zum Kompilieren und Ausführen eines jar-Files
* Script - run.sh
** Script nur fürs Ausführen eines jar-Files





== Besprochene Themen
* Jede einzelende Karte einlesen lassen und die ID, von den einzelen Karten davon aufschreiben.
* Bis zum nächsten Mal müssen wir eine Schleife programmieren, die darauf wartet ob eine Karte schon drauf gelegt wurde,
wenn ja dann sollte es angezeigt werden.







