  name: Quarkus Codestart CI

  on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 17
          uses: actions/setup-java@v1
          with:
            java-version: 17
        # Step that does that actual cache save and restore
        - uses: actions/cache@v1
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-
        - name: Build
          run: ./mvnw verify -B -DskipTests
        - name: install ssh key
          uses: webfactory/ssh-agent@v0.4.1
          with:
           ssh-private-key: ${{ secrets.NFCMEALSERVER }}
        - name: create .ssh/known_hosts
          run: |
              ssh-keyscan -H -t rsa -v ${{ secrets.NFCMEAL_IP }}  >> ~/.ssh/known_hosts
        - name: copy binaries to nfc-meal-counter
          run: |
                echo "Hallo ich bin hier"
                ls -l target/
                scp target/gh-actions-demo-4ahif-gr1-1.0.0-SNAPSHOT-runner.jar ${{ secrets.NFCMEAL_USER }}@${{ secrets.NFCMEAL_IP }}:



